export const countryFlags = [
	{ name: "Australia", flag: "https://flagcdn.com/w320/au.png" },
	{ name: "China", flag: "https://flagcdn.com/w320/cn.png" },
	{ name: "Japan", flag: "https://flagcdn.com/w320/jp.png" },
	{ name: "Bahrain", flag: "https://flagcdn.com/w320/bh.png" },
	{ name: "Saudi Arabia", flag: "https://flagcdn.com/w320/sa.png" },
	{ name: "USA", flag: "https://flagcdn.com/w320/us.png" },
	{ name: "Italy", flag: "https://flagcdn.com/w320/it.png" },
	{ name: "Monaco", flag: "https://flagcdn.com/w320/mc.png" },
	{ name: "Spain", flag: "https://flagcdn.com/w320/es.png" },
	{ name: "Canada", flag: "https://flagcdn.com/w320/ca.png" },
	{ name: "Austria", flag: "https://flagcdn.com/w320/at.png" },
	{ name: "UK", flag: "https://flagcdn.com/w320/gb.png" },
	{ name: "Belgium", flag: "https://flagcdn.com/w320/be.png" },
	{ name: "Hungary", flag: "https://flagcdn.com/w320/hu.png" },
	{ name: "Netherlands", flag: "https://flagcdn.com/w320/nl.png" },
	{ name: "Azerbaijan", flag: "https://flagcdn.com/w320/az.png" },
	{ name: "Singapore", flag: "https://flagcdn.com/w320/sg.png" },
	{ name: "Mexico", flag: "https://flagcdn.com/w320/mx.png" },
	{ name: "Brazil", flag: "https://flagcdn.com/w320/br.png" },
	{ name: "United States", flag: "https://flagcdn.com/w320/us.png" },
	{ name: "Qatar", flag: "https://flagcdn.com/w320/qa.png" },
	{ name: "UAE", flag: "https://flagcdn.com/w320/ae.png" },
];
