export const countryFlags = [
	{ name: "Australia", flag: "https://flagcdn.com/h60/au.png" },
	{ name: "China", flag: "https://flagcdn.com/h60/cn.png" },
	{ name: "Japan", flag: "https://flagcdn.com/h60/jp.png" },
	{ name: "Bahrain", flag: "https://flagcdn.com/h60/bh.png" },
	{ name: "Saudi Arabia", flag: "https://flagcdn.com/h60/sa.png" },
	{ name: "USA", flag: "https://flagcdn.com/h60/us.png" },
	{ name: "Italy", flag: "https://flagcdn.com/h60/it.png" },
	{ name: "Monaco", flag: "https://flagcdn.com/h60/mc.png" },
	{ name: "Spain", flag: "https://flagcdn.com/h60/es.png" },
	{ name: "Canada", flag: "https://flagcdn.com/h60/ca.png" },
	{ name: "Austria", flag: "https://flagcdn.com/h60/at.png" },
	{ name: "UK", flag: "https://flagcdn.com/h60/gb.png" },
	{ name: "Belgium", flag: "https://flagcdn.com/h60/be.png" },
	{ name: "Hungary", flag: "https://flagcdn.com/h60/hu.png" },
	{ name: "Netherlands", flag: "https://flagcdn.com/h60/nl.png" },
	{ name: "Azerbaijan", flag: "https://flagcdn.com/h60/az.png" },
	{ name: "Singapore", flag: "https://flagcdn.com/h60/sg.png" },
	{ name: "Mexico", flag: "https://flagcdn.com/h60/mx.png" },
	{ name: "Brazil", flag: "https://flagcdn.com/h60/br.png" },
	{ name: "United States", flag: "https://flagcdn.com/h60/us.png" },
	{ name: "Qatar", flag: "https://flagcdn.com/h60/qa.png" },
	{ name: "UAE", flag: "https://flagcdn.com/h60/ae.png" },
	{ name: "France", flag: "https://flagcdn.com/h60/fr.png" },
];
